# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

enable_passive: true
passive_key: CTRL
toggle_key: RIGHT_SHIFT
passive_arg_escape: "."
passive_arg_delimiter: ","
passive_match_regex: "(?P<name>:\\p{L}+)(:(?P<args>.*).)?"
exclude_default_entries: true
backspace_limit: 1
matches:
  # Dates
  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m-%d-%Y"
  - trigger: ":now"
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%m-%d-%Y_%H-%M"
  - trigger : "->"
    replace: "→"
  
  - trigger: "<-"
    replace: "←"
  
  - trigger : "-- "
    replace: "— "

  - trigger : "$up"
    replace: "↑"
  - trigger: "$do"
    replace: "↓"
  - trigger: "<_>"
    replace: "⟷"
  - trigger: "$check"
    replace: "✓"